[run]
command = "npm run dev"

[env]
NODE_ENV = "development"

[build]
command = "npm ci --production=false && npm run build"

[deployment]
command = "node dist/index.js"
directory = "."
publicPort = 5000
environment = "production"
build = true

[deployment.env]
NODE_ENV = "production"

[language]
name = "nodejs"
version = "20"

[nix]
channel = "stable-22_11"

[packager]
language = "nodejs"

[packager.features]
packageSearch = true
guessImports = true
enabledForHosting = false